### ISSUE TITLE
Add button to unlock attempt in the attempts overview page

### ISSUE THREAD

**Issue by izendegi** [vadimonus/moodle-quizaccess_onesession#13]
When a teacher has to unlock a session, the option is quite hidden (it's inside the block column - which is often collapsed - of the review attempt page), it would be easier to find and use if it'd be a button on the attempt review page (/mod/quiz/report.php?id=123456&mode=overview) next to the "Regrade selected attempts" and "Delete selected attempts" called "Unlock selected attempts"

**Comment by vadimonus** [comment]
@izendegi  , sorry this cannot be done. Currently moodle quizaccess plugins does not have ability to modify quiz reports. The only page that can be modified by this plugin type is attempt page. There's no other way, where to place this block.

Your idea can be done by implementing new cusstom quiz report plugin (taking overview report as base or example). But reaching this report will not be obvious too. Working with moodle is not simple and intiutively in many places, you anyway need to instruct teachers. So i have no plans to changing current plugin behaviour or implementing such report plugin.

**Comment by izendegi** [comment]
Hi @vadimonus 

This was only an improvement proposal, if there is no way to implement it within the plugin itself I understand we'll have to live with it the way it is, thank you!
